name: metaNanoPype
channels: 
- conda-forge
- bioconda
- r
dependencies: 
- python=3.6.9
- pip
- pip: 
    - matplotlib==3.1.3
    - tqdm==4.43.0
    - pandas==0.25.3
    - nanofilt==2.7.1
    - NanoPlot==1.29.1
    - seaborn==0.10.1 
- fastqc=0.11.5
- multiqc=1.9
- porechop=0.2.4
- kraken2=2.1.1
- r-base=4.0.3
- r-rmarkdown=2.7
- bioconductor-phyloseq=1.34.0
- r-dt=0.18
